### ISSUE TITLE
missing playlist actions

### ISSUE THREAD

**Issue by doka2212** [molobrakos/lms-mobileskin#1]
For daily use are some playlist-actions required.
- add to playlist
- clear playlist
- start from a song in playlist
- ...

**Comment by molobrakos** [comment]
Yes, thet are currently missing.
I discovered that for my daily use, 95% is covered by spotify/podcast/radio browsning, volume stuff and the syncing capabilites. So that is what got prioritized.
Do you have knowledge of Javascript? I would gladly accept Pull Requests that improved the app in this area!

**Comment by doka2212** [comment]
Thanks for the response. I will look into the code and maybe add some functionality.

**Comment by molobrakos** [comment]
Closing this for now, I consider this a well known issue and it is on the roadmap (I miss this functionality myself).
