### ISSUE TITLE
Unset theme

### ISSUE THREAD

**Issue by alexanderadam** [molobrakos/lms-mobileskin#8]
Thank you very much for the Skin.
Maybe you should do a PR to integrate it into the official repo after it gained some stability.

However, I've set the theme as default in the settings.
How can I undo this?

And how can I access the apps?
Every time I click on apps I get the following error:
```
jQuery.Deferred exception: menu.items is undefined browse_menu@http://lms.lan/m.js:387:5
browse_level/<@http://lms.lan/m.js:358:13
j@https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29997
g/</k<@https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313
 undefined
jquery.min.js:2:31569
```

**Comment by molobrakos** [comment]
Undoing the default skin: I don't know. Since there is no user interface for this, I guess you might have to manually edit the server settings file somewhere and restart the server.

The apps menu should now be fixed by https://github.com/molobrakos/lms-mobileskin/commit/b997bbafd9339abe1f699a5cd646fa10afaf85a4

**Comment by molobrakos** [comment]
Try visit http://server:9000/Default to access the default ui where you can change back

**Comment by alexanderadam** [comment]
Awesome. That was fast. Thank you!
